### ISSUE TITLE
x86-64 target architecture does not fetch runtime tarball

### ISSUE THREAD

**Issue by phatina** [RDunkley/meta-dotnet-core#19]
I am building an image for Up Squared board, which is 64-bit Intel and I fail to build `dotnet-core` package.

The fix which works for me is following:
```patch
diff --git a/recipes-runtime/dotnet-core/dotnet-core_3.1.3.inc b/recipes-runtime/dotnet-core/dotnet-core_3.1.3.inc
index efecb38..17f7493 100644
--- a/recipes-runtime/dotnet-core/dotnet-core_3.1.3.inc
+++ b/recipes-runtime/dotnet-core/dotnet-core_3.1.3.inc
@@ -7,7 +7,7 @@ HOMEPAGE = "https://dotnet.microsoft.com/download/dotnet-core/3.1"
 
 DOTNET_RUNTIME_ARCH = "none"
 DOTNET_RUNTIME_ARCH_arm = "arm"
-DOTNET_RUNTIME_ARCH_x86_64 = "x64"
+DOTNET_RUNTIME_ARCH_x86-64 = "x64"
 DOTNET_RUNTIME_ARCH_aarch64 = "arm64"
 
 # This is here because it doesn't seem like bitbake likes ${PV} used in require statements.
```

Am I doing something wrong? Is this a typo (`-` vs `_`)?

Thank a lot.

**Comment by RDunkley** [comment]
I keyed off the TARGET_ARCH in Yocto Reference manual to get these. Looks
like older reference manuals have the '-' while newer have the '_'. If you
are using an older version of poky then you may have other build issues,
but I don't see anything wrong with adding them both so that either
architecture string works.

**Comment by RDunkley** [comment]
Added this in 5.0.12 and will add for future versions.
