### ISSUE TITLE
Is development of this still active. We are moving to hardknot and want to use the latest asp-dotnet core with it. 

### ISSUE THREAD

**Issue by tbandtg** [RDunkley/meta-dotnet-core#30]
Hi I have used your layer before in a previous project, am moving that project to hardknot is this something you plan to support?

**Comment by RDunkley** [comment]
I haven't had as much time to maintain this project as I would like lately. I am planning on adding support for the latest 5.x and the new 6.0 versions in the near future. This project was always meant to be a stop gap until we can actually build the binaries (how it should be). Dotnet 6.0 has taken some steps to make this easier (with the new source build), unfortunately it doesn't look like cross compiling is there yet. As far as hardknot goes, I won't be moving my develop systems to it anytime soon, so I won't be able to add support for you. If you submit a PR I would be happy to accept it. It may be as simple as adding hardknot to layer.conf.

**Comment by indyIOT** [comment]
I understand, if it comes to that I will do it. For now though the latest version of 5.x would be great. I think I did this myself once but am not sure. If not that is fine too. I am becoming more familiar with how yocto build system works over time. We are only going to hardknott because our dotnet developer was having chrome lock up under zeus while his dotnet application was running. 

we have not ruled out that the problem might be one of the packages or layers that I added for the embedded side.

**Comment by indyIOT** [comment]
I tried adding it to our hardknott but I get build errors around opencv. I am going to try and figure it out because I know you guys are super busy. 

ERROR: Task (/opt/nfs_share/edm_yocto_hardknott/sources/meta-freescale/recipes-support/opencv/opencv_4.5.2.imx.bb:do_install) failed with exit code '1' 
Pseudo log:
Setup complete, sending SIGUSR1 to pid 1187132.
path mismatch [3 links]: ino 17712063 db '/opt/nfs_share/edm_yocto_hardknott/build-xwayland-edm-g-imx8mp/tmp/work/cortexa53-crypto-mx8mp-poky-linux/opencv/4.5.2.imx-r0/package/usr/src/debug/opencv/4.5.2.imx-r0/contrib/modules/intensity_transform/samples/intensity_transform.cpp' req '/opt/nfs_share/edm_yocto_hardknott/build-xwayland-edm-g-imx8mp/tmp/work/cortexa53-crypto-mx8mp-poky-linux/opencv/4.5.2.imx-r0/contrib/modules/intensity_transform/samples/intensity_transform.cpp'.

**Comment by indyIOT** [comment]
First thing I am going to do is pull out the special curl, as I do not think it is necessary for newer versions of dotnet-core.

**Comment by RDunkley** [comment]
It isn't. At some point we need to drop the older versions of dotnet-core and the curl bbappend.

**Comment by RDunkley** [comment]
Done in 0c8d41c3570c568dd0f885437d6c8c976ce4f776
