### ISSUE TITLE
add failed

### ISSUE THREAD

**Issue by HJK17** [RDunkley/meta-dotnet-core#31]
ERROR: Layer dotnet-core is not compatible with the core layer which only supports these series: honister (layer is compatible with sumo)

ERROR: Parse failure with the specified layer added, aborting.

**Comment by dougcooper** [comment]
im not seeing honister as a supported layer in this repo based on the local.conf

**Comment by RDunkley** [comment]
Honister has some breaking syntax changes that makes it incompatible with previous releases. Since Honister is the latest version a lot of people may still be using the older versions. For this reason, I created a new branch called Honister that should work with Honister and later. When the previous layers become deprecated then we can branch master to a legacy branch and move forward with Honister as Master.
