### ISSUE TITLE
Thud branch mixes old and new yocto syntax

### ISSUE THREAD

**Issue by vovanp** [RDunkley/meta-dotnet-core#36]
After latest commit in the thud branch, commit efcf20454fbf85055a0bf37aeb52aa7a748dc536 some files have new yocto syntax and therefor could not be compiled with the Thud branch.  
log: ERROR: ParseError at /meta-dotnet-core/recipes-devtools/vsdbg/vsdbg_17.0.10712.2.inc:12: unparsed line: 'RDEPENDS:${PN} += " procps"'

**Comment by RDunkley** [comment]
I fixed this on the master branch, but forgot to push to Thud. In the
meantime you should be able to use master.

**Comment by vovanp** [comment]
But how can I use Thud branch directly. It will be not possible to use master branch directly, because in the next yocto release the syntax will change.

**Comment by ghost** [comment]
I am targeting dunfell and was facing the exact same error. Using master fixed it, or at least made parsing successful.
However, it would be great to have it on the release branch.

**Comment by ghost** [comment]
> I am targeting dunfell and was facing the exact same error. Using master fixed it, or at least made parsing successful. However, it would be great to have it on the release branch.

Using the poky with version 3.1.14 fixed my issue.

**Comment by RDunkley** [comment]
I ended up keeping Master with the old syntax. Honister is the first
release with the new syntax so I decided to keep master as the old and
create a new branch for Honister.

So master should work right now for you until I can update thud. Moving
forward I plan on keeping Master the old syntax until a few more yocto
versions come out (since most users won't be on Honister yet).

**Comment by RDunkley** [comment]
It was way past time to move forward on post-Gatesgarth syntax. The main branch has been updated to Honister and above. If you need the old syntax, then use the pre-honister branch.
